// Hand-authored API tables drawn from packages/core/src/core/types.ts. These
// interfaces are type-erased at build time, so the option/method/attribute lists
// live here. They change rarely; keep them in step with types.ts.

export interface OptionRow {
  name: string;
  type: string;
  def: string;
  desc: string;
}
export const OPTIONS: OptionRow[] = [
  { name: 'host', type: 'FieldHost', def: 'required', desc: 'The environment seam (viewport, scroll, rAF, canvas). createField throws without it — pass browserHost() from @fundamental-engine/dom, or use @fundamental-engine/vanilla / the web component, which wire it for you.' },
  { name: 'accent', type: 'string', def: "palette's first stop", desc: 'The travelling accent color (a hex string).' },
  { name: 'density', type: 'number', def: '1', desc: 'Particle-count multiplier.' },
  { name: 'waves', type: 'boolean', def: 'false', desc: 'Draw the background Currents (the wave layers + bound shimmer). Opt-in (#979): a bare field has no carrier waves; pass true for the ambient resting structure.' },
  { name: 'waveStyle', type: "'linear' | 'circular'", def: "'linear'", desc: 'The wave current pattern. linear draws parallel horizontal waves; circular draws concentric orbits circling around the waveCenter or the star body. <field-root wave-style>.' },
  { name: 'waveCenter', type: "Vec2 | (() => Vec2) | null", def: 'null', desc: 'The center coordinate (or coordinate-provider fn) for circular waves. Defaults to the first body tagged with star or vortex, or the center of the field. <field-root wave-center> (space-separated, e.g. "200 300").' },
  { name: 'background', type: "'opaque' | 'transparent'", def: "'opaque'", desc: "Substrate background. 'transparent' clears to transparent instead of painting the near-black substrate, so the underlay composites over light content (an image, a 3D scene, a light page) — trails fade to transparent rather than to black. Also a <field-root background> attribute and live via setBackground." },
  { name: 'depth', type: 'number', def: '0', desc: 'Optional z volume. 0 (the default) is the flat field, byte-identical to the 2D engine; > 0 opens a shallow depth the matter drifts through, projected as a size/alpha recession. Purely additive — no API requires z.' },
  { name: 'integrator', type: "'legacy' | 'fixed' | 'velocity-verlet'", def: "'legacy'", desc: "Integration scheme (substrate doc 04 §Step 3, #659). 'fixed' opts into the partially frame-rate-corrected integrator: the FRICTION/HEAT_DECAY decays scale with dt (FRICTION^dt), so damping is consistent across frame rates — but by design it does NOT yet dt-scale force impulses (unsound for pair forces that mutate a neighbour in the same pass; deferred to the force-contract change, integrator.ts applyForce / doc-04 §Step 3); at the reference rate (dt === 1, and every golden/conformance run) it is byte-identical to the default 'legacy' semi-implicit Euler, so opting in never moves the golden. 'velocity-verlet' opts into the second-order velocity-Verlet scheme: the position full-step uses the previous step's stored acceleration (x += v·dt + ½·a·dt²), the force pass evaluates a′ at the updated position, and the velocity takes the half-step average (v += ½·(a + a′)·dt); kinematic velocity-replacing forces (jet/wall/lens/gate/warp) bypass the average as discontinuities, and decays are dt-scaled like 'fixed'. Higher positional accuracy, NOT a conservation guarantee (energy/momentum stay non-conserved by design; the per-step decay keeps it non-symplectic) — trajectories differ from 'legacy' by design once opted in. The default path never engages either mode. <field-root integrator>. Experimental." },
  { name: 'render', type: "'none' | 'dots' | 'trails' | 'links' | 'metaballs' | 'voronoi' | 'streamlines' | 'flow' | 'knockout' | 'redshift' | 'blackbody' | 'depth'", def: "'none'", desc: "Render mode for the underlay surface (behind content) — the same physics drawn differently. The default is 'none' (#538): the signals-only engine runs the full simulation + feedback (--d, --load, capture events) but draws nothing — the field is behavior first. Opt into a visible surface with 'dots' (particles) or another mode." },
  { name: 'overlay', type: "OverlayMode | OverlayMode[]", def: "'off'", desc: 'Field Surfaces: the overlay READING(S) drawn in front of content (see the overlay-readings table) — one reading or an additive stack. Set alongside render. <field-root> manages the front canvas (space-separated tokens in the attribute); for createField directly, pass overlayCanvas.' },
  { name: 'gridWarp', type: 'number', def: '1', desc: 'Distortion multiplier for the grid overlay (the reference lattice displaced by the field). 1 is the calibrated "legible, never chaotic" deflection; 2–3 exaggerates the deformation for demos; 0 flattens the lattice. Only affects the grid overlay mode. <field-root grid-warp>.' },
  { name: 'gridIntensity', type: 'number', def: '0.16', desc: 'Stroke intensity (opacity) of the grid overlay lattice ∈ [0,1] — turns the warped grid from a faint diagnostic into a visual centerpiece (#552). 0.16 is the calibrated default; raise it (~0.4) to make the bending space the hero of a section. Only affects the grid overlay mode. <field-root grid-intensity>.' },
  { name: 'bounds', type: 'HTMLElement', def: 'window', desc: 'Contained fields (#540): scope the field to a single element instead of the viewport. A vanilla createField / new FieldField option — the field measures and renders inside the given element (a card, a panel), so a component can carry its own local field. Omit for the default full-window field. (containerHost() is the lower-level door.)' },
  { name: 'mass', type: 'boolean', def: 'false', desc: 'First-class mass: particle mass ∝ size and body forces accelerate by a = F/m; dynamic bodies also get inertial mass ∝ rendered area (#872).' },
  { name: 'reaction', type: 'boolean', def: 'false', desc: 'Newtonian own-emission reaction (#873): a dynamic body feels the equal-and-opposite of the net impulse it imparts to nearby matter (a directional emitter recoils like a rocket). Best paired with mass. Experimental.' },
  { name: 'palette', type: 'string | string[]', def: "'ours'", desc: 'Accent template — a built-in name or custom hex stops.' },
  { name: 'theme', type: 'string', def: "'warm'", desc: "Ambient theme preset — 'warm' | 'cool' | 'mono'. Sets the free-particle heat ramp and the background-wave baseline (distinct from the travelling accent). 'warm' reproduces the shipped default." },
  { name: 'gradientCool', type: 'string', def: "theme's", desc: 'Hex for the cool (resting) end of the free-particle heat ramp — overrides the theme. <field-root gradient-cool>.' },
  { name: 'gradientWarm', type: 'string', def: "theme's", desc: 'Hex for the warm (energized) end of the heat ramp — overrides the theme. <field-root gradient-warm>.' },
  { name: 'waveBaseline', type: 'string[]', def: "theme's", desc: 'Hex stops for the background-wave baseline — overrides the theme. <field-root wave-baseline> (space-separated).' },
  { name: 'attention', type: 'boolean', def: 'false', desc: 'Conserved attention — one finite strength budget; engaging a body starves the others.' },
  { name: 'causality', type: 'boolean', def: 'false', desc: 'Cross-boundary causality — a saturated body spills density to its neighbours.' },
  { name: 'heatmap', type: 'boolean', def: 'false', desc: 'Density heatmap — a glow layer of where matter pools, sampled back to bodies as --field-heatmap-density.' },
  { name: 'separation', type: 'number', def: '0', desc: 'Strength of short-range particle-to-particle separation/repulsion force ∈ [0,1] to break up clumps in high-density areas. <field-root separation>.' },
  { name: 'ambientOrbit', type: 'number', def: '0.1', desc: 'DECLARED ambient bias (Wallpaper Rule, #978): the resting ambient formation\'s tangential swirl injected into attract bodies — the gentle spiral free matter traces around a well at rest. Formerly a hardcoded 0.1 painted into the default formation preset; now a documented dial defaulting to that value (resting behavior unchanged). Set 0 for a purely radial attract (no spiral). Applies to the ambient formation only. <field-root ambient-orbit>.' },
  { name: 'ambientWander', type: 'number', def: '1.0', desc: 'DECLARED ambient bias (Wallpaper Rule, #978): the resting ambient formation\'s wander term — the per-particle drift that keeps resting matter alive rather than frozen. Formerly a hardcoded 1.0 in the default formation preset; now a documented dial defaulting to that value (behavior unchanged). Lower for a calmer rest, 0 to still the drift. Applies to the ambient formation only. <field-root ambient-wander>.' },
  { name: 'overlayCanvas', type: 'HTMLCanvasElement', def: 'undefined', desc: 'Field Surfaces: a caller-provided canvas for the overlay surface (drawn in front of content). The web component creates/manages this for you; pass it only when calling createField directly.' },
  { name: 'overlayCanvasProvider', type: '() => HTMLCanvasElement | null', def: 'undefined', desc: 'Field Surfaces: a lazy alternative to overlayCanvas (#676). When no overlayCanvas is set, core calls this once — the first time an overlay reading actually goes active — to obtain the surface. Lets a host defer creating its full-viewport mix-blend canvas until an overlay is switched on, so the common overlay:off path never adds a canvas to the compositing tree at boot. <field-root> uses this internally; return null to decline. Ignored when overlayCanvas is set.' },
  { name: 'feedbackSink', type: 'FeedbackSink', def: 'undefined', desc: 'Advanced: route per-body density/feedback writes to the platform FeedbackRegistry instead of letting the engine write the DOM (Phase D3).' },
  { name: 'dprCap', type: 'number', def: '2', desc: 'Backing-store device-pixel-ratio ceiling (#410) — the dominant fill-rate lever. Effective DPR = min(devicePixelRatio, dprCap); capping at ~1.5 buys ~1.8× headroom on retina for a small perceptual softening. Runtime-settable via setDprCap. <field-root dpr-cap>.' },
  { name: 'overlayBackend', type: 'RenderBackend', def: 'Canvas 2D', desc: 'Drawing backend for the overlay surface (#373) — the structural seam a WebGL/WebGPU surface implements. Defaults to the Canvas 2D implementation over overlayCanvas. See render-backend.ts.' },
  { name: 'rng', type: '() => number', def: 'Math.random', desc: 'Random source for ALL engine randomness — particle seeding, spawn scatter, jitter, release angles (#371). Supply a seeded generator to make a run reproducible (the record/replay seam).' },
  { name: 'now', type: '() => number', def: 'performance.now', desc: 'Wall-clock source for input-idle tracking (#371) — one of the three engine clocks (wall / frame / simulation). Defaults to performance.now; override in tests or replay harnesses.' },
  { name: 'policy', type: 'FieldPolicy', def: 'undefined', desc: 'Runtime FIELD POLICY — what THIS host/session/user/app PERMITS at runtime (distinct lane from governance, which is what doctrine allows via static lint). FieldPolicy { allowBodyDataInSnapshots?, allowMotionProjection?, maxMotionBudget? (0..1), budgets?: Partial<FieldBudgets> }; FieldBudgets bounds consumable resources: motion/force/attention/thermal/render/privacy/accessibility/agentRead. WIRED today: the motion budget folds (via min) with reduced-motion + perf pressure into the effective motion the integrator/easing reads — reduced-motion always wins (a policy can lower motion, never raise it); the privacy budget (+ allowBodyDataInSnapshots) gates body data in snapshot(). Other budgets are declared-not-yet-enforced. Change it live with setPolicy. Purely additive — a field with no policy behaves exactly as before.' },
  { name: 'identify', type: '(el: HTMLElement) => FieldBodyIdentity | undefined', def: 'undefined', desc: 'First-class body identity resolver: derive a stable, structured FieldBodyIdentity ({ id, namespace?, kind?, host? }) from a DOM-scanned body\'s element, called once per body. The identity is surfaced on query()/snapshot() body readings and used as the stable key for diff/replay/relationships. Return undefined to fall back to the default derivation (the element DOM id, else a monotonic body-N). Purely additive — a field without identify behaves exactly as before.' },
];

export interface MethodRow {
  sig: string;
  desc: string;
}
export const HANDLE: MethodRow[] = [
  { sig: 'scan()', desc: 'Re-scan the document for [data-body] bodies after a DOM change.' },
  { sig: 'rescan()', desc: 'Alias of scan().' },
  { sig: 'setAccent(hex)', desc: 'Recolor the travelling accent.' },
  { sig: 'setPalette(name | hex[])', desc: 'Swap the accent color template live.' },
  { sig: 'setFormation(name)', desc: 'Switch the global formation.' },
  { sig: 'setWaveStyle(style)', desc: "Switch the wave current layout style live ('linear' | 'circular')." },
  { sig: 'setWaveCenter(center)', desc: 'Set the custom wave center coordinate ({x, y} or function) live.' },
  { sig: 'setSeparation(strength)', desc: 'Set particle-to-particle separation/repulsion force strength live.' },
  { sig: 'setAttention(on)', desc: 'Toggle conserved attention live (one finite strength budget).' },
  { sig: 'setCausality(on)', desc: 'Toggle cross-boundary causality live (density spills to neighbours).' },
  { sig: 'setHeatmap(on)', desc: 'Toggle the density heatmap layer live (a glow of where matter pools).' },
  { sig: 'setDprCap(cap) / opt dprCap', desc: 'Backing-store DPR ceiling (#410) — the dominant fill-rate lever. Effective DPR = min(devicePixelRatio, dprCap), default 2; capping at ~1.5 buys ~1.8x headroom on retina for a small softening. As a FieldOptions key (createField / <field-root dpr-cap>) or the runtime setDprCap setter (re-sizes immediately). Shipped-but-unfrozen.' },
  { sig: 'setPolicy(policy) / policy / opt policy', desc: 'Runtime FIELD POLICY — what THIS host/session/user/app PERMITS (distinct lane from governance = what doctrine allows via static lint). setPolicy REPLACES (not merges) the live policy ({} clears to the unbounded default); field.policy reads a frozen copy. FieldPolicy carries allowBodyDataInSnapshots / allowMotionProjection / maxMotionBudget (0..1) / budgets (Partial<FieldBudgets>: motion, force, attention, thermal, render, privacy, accessibility, agentRead). WIRED: the motion budget folds (via min) with reduced-motion + perf pressure into the effective motion the integrator/easing reads — reduced-motion always wins (a policy can lower motion, never raise it); the privacy budget (+ allowBodyDataInSnapshots) gates body data in snapshot(). Other budgets declared-not-yet-enforced. Purely additive. Shipped-but-unfrozen.' },
  { sig: 'setQualityTier(tier)', desc: 'Adaptive quality (#413): drop the field to a cheaper tier (0 full → 3 lightest) reversibly. Maps the tier to the engine\'s own fill levers — caps the effective backing-store DPR (1.5 / 1.25 / 1) and skips the heaviest ambient layer (the heatmap glow) at tier 2+. <field-root> wires this automatically from the QualityGovernor on sustained frame-budget overruns; call it yourself to drive quality from your own signal. Shipped-but-unfrozen.' },
  { sig: 'setRender(mode)', desc: 'Switch the underlay render mode (behind content): dots / trails / links / metaballs / voronoi / streamlines / flow / knockout / redshift / blackbody / depth.' },
  { sig: 'setOverlay(mode | mode[])', desc: 'Field Surfaces: render overlay reading(s) in front of content — one reading or an additive stack (the readings compose). The vocabulary: streamlines / force-vectors / field-lines / grid / temperature / energy / path / data, or off. Pairs with setRender.' },
  { sig: 'setBackground(mode)', desc: "Switch the substrate live: 'transparent' clears to transparent so the underlay composites over light content; 'opaque' restores the near-black substrate. Additive." },
  { sig: 'threads(list | null)', desc: 'Wire glowing connector lines between an engaged set, or clear with null.' },
  { sig: 'burst(x, y, hex?)', desc: 'A one-shot shove + heat near a point, optionally tinting the matter.' },
  { sig: 'flowTo(x, y, opts?)', desc: 'Place/move a dynamic flow focus the field bends toward — pulls matter in and curves the streamlines. Retarget it each frame to follow the pointer, an element, or a path. opts: { strength?, radius? }.' },
  { sig: 'clearFlow()', desc: 'Remove the flow focus — the field relaxes back to its bodies-only shape.' },
  { sig: 'seed(atoms)', desc: "Bind a data record to each base particle, round-robin. Each record's weight ∈ [0,1] scales that particle's mass + size. Re-applied across resize/density rebuilds." },
  { sig: 'atomAt(x, y)', desc: 'The seeded record on the nearest particle to (x, y) within ~24 px, or null. For hover-to-inspect.' },
  { sig: 'focusAt(x, y)', desc: 'Hold + highlight the nearest seeded particle; return its record — the dwell affordance before a click. Returns null if no particle is in range.' },
  { sig: 'clearFocus()', desc: 'Release the focused particle; it resumes drifting.' },
  { sig: 'version (property)', desc: 'Readonly string — the running engine version (= FIELD_VERSION), i.e. which build this field is on (#547). For a consumer that wants to assert or log the engine it loaded. Shipped-but-unfrozen.' },
  { sig: 'particleCount()', desc: 'Live size of the particle pool. Use for external budget monitors or debug overlays without walking the particle array. Shipped-but-unfrozen.' },
  { sig: 'energy()', desc: 'Per-frame energy snapshot: { kinetic, thermal, total, count }. Forwards to energyReport() without requiring a reference to the internal particle array. Shipped-but-unfrozen.' },
  { sig: 'readParticles(out)', desc: 'Copy live particle state into a caller-owned Float32Array (stride 5: x, y, z, heat, size — z is the optional depth lane, 0 in a flat field); returns the count written = min(particleCount(), floor(out.length/5)). Zero-alloc and read-only — the render-agnostic swarm read-out an alternative surface (e.g. @fundamental-engine/three) draws from. Shipped-but-unfrozen; the stride may widen (a color lane) before 1.0.' },
  { sig: 'readParticleIds(out)', desc: 'Copy each live particle\'s stable id into a Uint32Array, parallel to readParticles (same order, same agent skip), so ids[i] is the identity of the particle at stride offset i*5. Lets a host track a seeded entity across frames and key its own opaque payload off the id. Zero-alloc, read-only. Shipped-but-unfrozen.' },
  { sig: 'sample(x, y)', desc: 'The net field force a still test particle would feel at (x, y), as { x, y } in field-pixel space — every visible body superposed (wells, dipole structure, flow bias). Pure and read-only, samplable at any resolution; the seam external visualizers consume for vector grids, streamline tubes, or mesh displacement. Shipped-but-unfrozen.' },
  { sig: 'sampleScalar(x, y)', desc: 'The smooth diffused density scalar ∈ [0,1] at (x, y) — the heatmap grid, bilinear-sampled, so its gradient stays meaningful at a source (forage-by-gradient), unlike a nearest-body readout. Requires the heatmap layer (createField({ heatmap: true }) / setHeatmap(true)); returns 0 when off. Read-only, updated each frame including under render:none. Shipped-but-unfrozen.' },
  { sig: 'sampleGradient(x, y)', desc: 'The gradient ∇ {x,y} of the density field at (x, y) — direction + steepness (1/px) of increasing matter density. The analytic companion to sampleScalar, off the same diffused heatmap grid, so it stays non-degenerate at a source (a real uphill slope where a nearest-body density flattens to zero) — the cue reliable forage-/flee-by-gradient steers by. Requires the heatmap layer; returns { x: 0, y: 0 } when off or empty. Pure, read-only, maintained under render:none. Shipped-but-unfrozen.' },
  { sig: 'grid(name)', desc: 'Open a named host-authorable ScalarGrid — the engine field-buffer primitive (the same one diffuse/memory/propagate run on), promoted to a public surface for application fields the simulation composes with (a scent map, a wear/desire-path layer, a goal attractor). { sample, deposit, gradient, decay, clear } in field px. Created on first access, kept viewport-sized, advanced each frame by its mode (wave… = wave, memory… = slow decay, else diffuse); a same-named force shares the buffer. Shipped-but-unfrozen.' },
  { sig: 'on(type, cb)', desc: 'Subscribe to a discrete field event — the host-agnostic push bus, for reacting to occurrences instead of polling feedback channels each frame. Returns an unsubscribe fn; plain data, no DOM. Discrete events are thresholded, debounced, and lazy. `absorb`/`release` report sink accretion; `enter`/`exit`/`met` report proximity and contact; additional `field:*` events report threshold crossings (attention, entropy, memory, saturation) where supported. `settle` remains reserved/planned. Shipped-but-unfrozen.' },
  { sig: 'addAgent(spec)', desc: 'Add an engine-stepped agent — a participant the integrator MOVES (vs sample(), where you integrate yourself). It lives in the particle pool, so it feels every force the swarm feels (body forces AND particle-level hunt/align/cohesion); each step its report(p) fires so an external transform (a THREE.Object3D) follows it. spec: { x, y, z?, mass?, maxSpeed?, species?, report }. maxSpeed caps it, species lets tagged bodies (data-affects) steer it selectively; it edge-bounces (not wraps) and is excluded from readParticles. Returns { particle, remove() }. The creatures primitive @fundamental-engine/three\'s layer.addAgent binds over. Shipped-but-unfrozen.' },
  { sig: 'addBody(spec)', desc: 'Add a programmatic body (no DOM) from a spec — the sanctioned alternative to the [data-body] scan for a non-DOM host (Three.js mesh, native view). { tokens, strength?, range?, spin?, angle?, color?, rect:()=>box, data?, onFeedback? }; rect() samples the box in field px each frame. The body carries a data record and takes per-body feedback (channels demuxed from the global sink); survives rescan. Returns { data, channels, set(params), remove() } — set({ strength?, range?, angle?, spin?, color? }) mutates the force params live on the measure cadence (no rescan, no remove+re-add; a token change still needs remove+addBody). Shipped-but-unfrozen.' },
  { sig: 'addEdge(a, b, opts?)', desc: 'Relate two programmatic bodies — the non-DOM relationship counterpart of addBody (a, b are addBody handles). The edge carries a live RelationshipAgent: it STRENGTHENS while its source body is salient (gathering matter) and decays while idle, accumulating memory — so a non-visual consumer (an agent modelling file↔meeting↔app) gets the relationship layer + its longitudinal warmth, with no DOM. opts: { type?, strength?, direction? }. Returns an EdgeHandle { set({ strength?, type? }), remove() }; read the live graph back with readEdges(). Shipped-but-unfrozen.' },
  { sig: 'readEdges()', desc: 'The live programmatic-edge read-out (addEdge) for a non-visual consumer — an array of { from, to (the endpoint bodies\' data records), type, strength, memory, active }. Pure, read-only: the relationship graph + its dynamics the way readParticles is the swarm. Shipped-but-unfrozen.' },
  { sig: 'query(q?)', desc: 'Ask the live field a structured question and get back plain, serializable data — the agent-/tool-/test-readable surface. q = { at?, radius?, include? }: at is a point ({x,y}), a DOMRect-shaped rect ({x,y,width,height}, so el.getBoundingClientRect() drops straight in), or omitted for a whole-field query; radius (default 240) sizes a point query; include picks sections (bodies | metrics | relationships | influences). Returns { frame, time, region?, bodies, metrics, relationships, influences } — bodies carry id/rect/tokens/metrics/dimensions/activeFormations, relationships are the edge graph by id, and influences attribute per-force contribution at the point (from the impulse accumulator) — each carries a `channel` (`linear` Δv or `thermal` heat, doc 04 §Step 6). Read-only and render-agnostic (works headless). EXPERIMENTAL — not yet in the frozen surface.' },
  { sig: 'snapshot(opts?)', desc: 'Capture what the field is DOING at this frame — a portable, serializable FieldSnapshot (vs a screenshot of what it looked like). Returns { id, createdAt, frame, version, formations, bodies, relationships, metrics, particles? } — bodies carry id/rect/position/tokens/metrics/dimensions (+ data with includeData). opts: { includeParticles?, includeRelationships? (default true), includeData? (default false), includeInfluences? (per-body force attribution, for replay force steps), profile? }. profile (SnapshotProfile = debug | agent | bug-report | public) is a concrete inclusion preset composed with the explicit include* flags + the privacy policy, always resolving to the TIGHTEST (most private) result — a profile can never widen past what policy or an explicit deny allows (debug = everything; agent = ids + metrics + relationships + influences + projections, NO opaque body data; bug-report = structural + versions; public = ids + shape). Read-only; works headless; format is versioned (FIELD_VERSION). Pair with diff(). EXPERIMENTAL.' },
  { sig: 'forAgent(opts)', desc: 'Derive a scoped, READ-ONLY AgentFieldView — the safe surface a Software Agent uses to read the field (agent-readable is NOT agent-writable). forAgent({ capabilities, redactions? }) returns a facade exposing ONLY scoped query() / snapshot() (+ replay() only when read:replay is granted); it has NO mutation methods (no applyForce/addBody/setPolicy), enforced by the facade shape. AgentCapability = read:metrics | read:relationships | read:influences | read:snapshots | read:body-data | read:projections | read:diagnostics | read:replay — an allow-list; a dimension not granted is stripped from every reading (tightens, never widens: no read:influences → influences stripped; no read:body-data → body.data withheld even if a profile/includeData asked for it). redactions?: string[] strips dotted paths (body.data, host.user, metrics.temperature) AFTER capability scoping. Respects FieldPolicy: budgets.agentRead === 0 closes the surface to the most-restricted view (the fractional gradient is a declared seam). EXPERIMENTAL.' },
  { sig: 'diff(a, b)', desc: 'Compare two snapshots and report what changed in the field, by lane: { from, to, bodyChanges (added/removed/changed metrics), relationshipChanges (strength/active deltas), metricChanges, formationChanges (activated/deactivated) }. Pure (operates on the two snapshots, ignores live state) — the standalone diffFieldSnapshots(a, b) is also exported. EXPERIMENTAL.' },
  { sig: 'replay(a, b, opts?)', desc: 'Explain HOW the field changed between two snapshots — an ordered, narrated sequence of causes derived from the diff: { from, to, focus?, steps } where each step is { frame, time, cause (formation | relationship | metric | measurement | force), source?, target?, description, contribution? }. e.g. "Formation \'wells\' activated", "Relationship A→B strengthened 0.10→0.40", "Body claim-3 density rose 0.20→0.60". opts.focus scopes it to one body id. Pure (derived from the two snapshots) — the standalone replayFieldSnapshots(a, b, opts) is also exported. When both snapshots were captured with includeInfluences, replay also emits cause=force steps (which force grew/weakened/engaged/released, by channel incl. thermal). The substrate explainability layer (Causal Replay). EXPERIMENTAL.' },
  { sig: 'projections', desc: 'The projection registry (substrate 05) — a property, not a method. A projection maps field STATE to an output surface (CSS / dom-attribute / annotation / agent-json / reduced-motion / sound / haptic / …), declaring its channels, surfaces, and reducedMotion/accessibility equivalents. register(p) → unregister fn; unregister(id); get(id); list() → serializable metadata; apply(id, reading, target) writes the reading to a surface; lint() runs governance accessibility checks over the registry (field/reduced-motion-equivalent-required = error, field/accessibility-equivalent-required = warning; the standalone lintProjections() is also exported). Governance principle: projection REVEALS state, it never changes it (no forces). query()/snapshot() report the registered projections. EXPERIMENTAL.' },
  { sig: 'addField(name, sampler)', desc: 'Register a named field CHANNEL — an external scalar field the engine samples on its own read path (terrain height, soil moisture, a heat map). The open INPUT analog of the render surfaces (setRender/setOverlay are bundled output layers): instead of bolting a parallel grid alongside the field, hand it a pull-based sampler (x, y) => number and read it back through sampleField, so a consumer queries ONE field, not two. The sampler is called on demand (never cached) — keep it cheap. Returns a FieldChannelHandle { name, set(sampler), remove() } to swap the sampler live or unregister. (Force coupling — a force reading a channel as a potential — is a separate opt-in; this is the read substrate.) Shipped-but-unfrozen.' },
  { sig: 'sampleField(name, x, y)', desc: 'Sample a channel registered with addField at (x, y) in field-pixel space; returns 0 for an unregistered channel. Pure, read-only. Shipped-but-unfrozen.' },
  { sig: 'readParticleChannels(channels, out)', desc: "Read multiple named channels from live particles into caller-owned Float32Array buffers (column-wise: all particles' first channel, then second, etc.). Returns the particle count written. Channels: 'x' | 'y' | 'z' | 'vx' | 'vy' | 'heat' | 'size' | 'm' | 'id' | 'age' | 'charge'. Unknown channels write 0. Mirrors readParticles() agent-exclusion behavior. Zero-alloc alternative to readParticles when you need a subset of channels. Shipped-but-unfrozen." },
  { sig: 'registerOverlay(name, drawFn)', desc: 'Register a named custom overlay function — extends setOverlay beyond the built-in reading stack. Called each frame when name is in the active overlay stack (via setOverlay). drawFn receives the active RenderBackend, current Env, and canvas W/H. Returns an unregister function. Lets third-party packages (e.g. @fundamental-engine/three) publish custom overlay modes the host switches in by name. Shipped-but-unfrozen.' },
  { sig: 'scrollV()', desc: "The engine's eased page-scroll velocity — the same EMA the scrolling condition gate reads: (prev × 0.7) + (|Δscroll| × 0.3) per frame. Units are px/frame at the display refresh rate (refresh-rate dependent — roughly half on 120 Hz; may normalize to px/ms before 1.0). Mirrored to --field-scroll-v on :root by the platform runtime. Pull-based: read on demand, don't poll in tight loops. Shipped-but-unfrozen." },
  { sig: 'setVisible(on)', desc: 'Element-level visibility hint: setVisible(false) skips all draw work (render + overlay) each frame while the simulation and its feedback signals stay live — scrollV(), --d, --load, capture events keep flowing. Distinct from the tab-level pause (visibilitychange already stops the loop entirely). <field-root> wires it automatically from an IntersectionObserver on the host. Shipped-but-unfrozen.' },
  { sig: 'destroy()', desc: 'Stop the loop and release listeners.' },
];

export interface AttrRow {
  name: string;
  type: string;
  def?: string;
  desc: string;
}
export const ATTRS: AttrRow[] = [
  { name: 'data-body', type: 'tokens', desc: 'Space-separated force ids — required to make an element a body. Forces compose.' },
  { name: 'data-strength', type: 'number', def: '0.5', desc: 'Force magnitude S.' },
  { name: 'data-range', type: 'px', def: '280', desc: 'Influence radius d_max.' },
  { name: 'data-spin', type: 'number', def: '1', desc: 'Sign/strength of rotation — swirl, charge, magnetism, lens.' },
  { name: 'data-angle', type: 'deg', def: '0', desc: 'Heading — stream, jet, gate, shear, align.' },
  { name: 'data-color', type: 'hex', desc: 'Accent override on engage, and the carried color for pigment.' },
  { name: 'data-when', type: 'condition', def: "''", desc: 'Gate the force on a condition: active, fast, slow, hot, cool, scrolling.' },
  { name: 'data-feedback', type: 'flag', desc: 'Opt into two-way density write-back (the --d custom property).' },
  { name: 'data-shaped', type: 'flag', desc: 'Shaped source — forces reference the nearest point on the element box, so matter shells the shape instead of bunching at its centre.' },
  { name: 'data-charge-gated', type: 'flag', desc: 'Opt-in fieldflow mode (magnetized plasma) — the fieldflow force follows only charged matter (charge ≠ 0) so it composes with charge; neutral matter drifts free. Omit for the default, which advects ALL matter (neutral-medium transport).' },
  { name: 'data-authority', type: 'anchored | kinematic | dynamic', def: 'anchored', desc: 'Body-authority (substrate doc 04) — who owns the body position. anchored (default) measures from the DOM/host rect; kinematic = the engine writes the visual transform (the data-move pattern); dynamic = the engine owns position/velocity and the body moves — it integrates under the net field each frame (recoil / field-to-body coupling, doc 04 Step 5); momentum-recoil from own emission + torque are later refinements. Reported by query()/snapshot(). Experimental.' },
  { name: 'data-affects', type: 'species', desc: 'Matter tagging — a comma-separated species set this body acts on (e.g. "1" or "1,2"). Matter whose species is outside the set is skipped entirely (no force, no density sample). Omit to act on all matter (the default). Lets pollen / seeds / spores share one field, each pulled only by its own bodies.' },
  { name: 'data-species', type: 'number', desc: 'The species tag a spawn source stamps on the matter it emits, so a downstream data-affects body can act on it selectively. Particles default to species 0.' },
  { name: 'data-absorb', type: 'px', def: '64', desc: 'Capture radius for the sink force.' },
  { name: 'data-max', type: 'number', def: '60', desc: 'Load at which a sink supernovas (releases).' },
  { name: 'data-life', type: 'frames', def: '90 (spawn)', desc: 'Source budget: how long each particle a spawn source emits lives. An unbudgeted source gets the safe default 300 (and a dev warning).' },
  { name: 'data-cap', type: 'number', desc: 'Source budget: the most live particles a spawn source sustains — the emission rate is clamped to cap/life. The unbudgeted-source safe default is 120.' },
  { name: 'data-screen-min', type: 'number', def: '0', desc: 'Floor of the screen modifier\'s attenuation factor (0 = other forces may cancel fully at the screen\'s core).' },
  { name: 'data-fmin / data-fmax', type: 'number', desc: 'Variable-font weight range that --d drives on a feedback body.' },
  { name: 'data-opsz', type: 'number', desc: 'Optical-size axis to drive alongside weight.' },
  { name: 'data-active', type: '"1"', desc: 'Engagement state — set automatically on hover/focus of a [data-hot] element.' },
  { name: 'data-preset', type: 'name', desc: 'Expand a preset into several co-located bodies — blackhole, galaxy, tornado, …' },
  { name: 'data-pair', type: 'selector', desc: 'Warp force: CSS selector for the partner body (the other end of the wormhole). Matter that enters this body is teleported to the partner. Omit on non-warp bodies.' },
  { name: 'data-twist', type: 'deg', def: '0', desc: 'Warp force: rotation applied to matter crossing the throat — twist the exit angle.' },
  { name: 'data-scale', type: 'number', def: '1', desc: 'Warp force: scale factor applied to matter velocity when it exits the partner throat.' },
  { name: 'data-budget', type: 'flag', desc: 'Source budget flag — marks a spawn source as explicitly budgeted without specifying data-life or data-cap. Suppresses the unbudgeted-source dev warning.' },
  { name: 'data-sink', type: 'flag', desc: 'Secondary budget indicator for a spawn source — if present, the engine treats the source as budgeted (equivalent to data-budget). Useful when paired with the sink force.' },
  { name: 'data-intent', type: 'intent', desc: 'Semantic authoring: a plain-language intent (e.g. "highlight" or "warn") that the engine compiles into the body\'s forces. When set, data-body is optional — the intent provides a default token + strength.' },
  { name: 'data-intensity', type: 'number', def: '1', desc: 'Modifier for data-intent: scales the compiled strength (0 = subtle, 1 = default, 2 = strong). Ignored when data-body is set directly.' },
  { name: 'data-risk', type: "'low' | 'medium' | 'high'", desc: 'Intent hint for data-intent compilation — tunes the body\'s compiled forces when the intent has risk-sensitive variants.' },
  { name: 'data-field-role', type: "role", desc: 'Semantic role: source / sink / anchor / boundary / sensor / display. Maps the element to a default body token and feedback (data-body is optional). sensor/display are feedback-only (no force).' },
  { name: 'data-field-boundary', type: 'flag (engine-set)', desc: 'Field-ownership marker — ENGINE-SET by a contained host (containerHost / the bounds: option) on its bounds element, not authored. A body belongs to the NEAREST enclosing marked boundary: outer/page-field scans skip bodies inside it, the contained field owns exactly its subtree, and nesting resolves to the nearest. Removed on destroy so the outer field re-adopts on rescan.' },
];

/** The CSS custom properties the field writes back onto bodies — the reciprocal half of the
 *  loop (the field measures, then writes state into the elements that made it). Read these in
 *  your own CSS to make an element answer the field. Written only to bodies that opt in. */
export const WRITEBACK: { name: string; on: string; desc: string }[] = [
  { name: '--d', on: 'data-feedback', desc: "The body's own gathered density ∈ [0,1], eased. The canonical reaction var." },
  { name: '--field-density', on: 'data-feedback', desc: 'Namespaced alias of --d (same value).' },
  { name: '--field-heatmap-density', on: 'data-feedback + heatmap', desc: 'The ambient heatmap density under the body ∈ [0,1] — where matter pools around it, distinct from --d.' },
  { name: '--load', on: 'sink body', desc: "A sink's accretion fill fraction ∈ [0,1] — rises as the sink captures matter, peaks at data-max, then supernovas (releases). The live level indicator for a capturing body." },
  { name: '--mass', on: 'sink body', desc: 'Back-compat alias of --load — same value, same semantics. Prefer --load in new stylesheets; --mass is kept for existing consumers.' },
  { name: '--lit', on: 'causality', desc: 'Spillover-lit density when a saturated neighbour bleeds density across a boundary.' },
  { name: '--entropy', on: 'data-feedback', desc: 'Measured local disorder ∈ [0,1] — velocity-direction dispersion, gated by agitation (physics workover v0.3). Engine-measured; distinct from the platform\'s inferred --field-entropy lane.' },
  { name: '--coherence', on: 'data-feedback', desc: 'Measured local order ∈ [0,1] (= 1 − entropy; velocity alignment). Numeric — not the --coherence palette color on :root.' },
  { name: '--temperature', on: 'data-feedback', desc: 'Measured local agitation ∈ [0,1] — half mean heat, half normalized kinetic energy.' },
];

export const RENDER_MODES: { name: string; desc: string }[] = [
  { name: 'dots', desc: 'The default — each particle a soft dot, cool centre → warm edge → accent.' },
  { name: 'trails', desc: 'Light-painting — particle history persists and fades.' },
  { name: 'links', desc: 'Constellation — lines drawn between nearby particles.' },
  { name: 'metaballs', desc: 'A liquid iso-surface — the swarm rendered as one molten skin via marching squares, not dots.' },
  { name: 'voronoi', desc: 'Shattered glass — each particle owns a cell; the walls are the boundaries between nearest-neighbour regions.' },
  { name: 'streamlines', desc: 'Draws the force field itself — a grid of arrows along the net push. A diagnostic view, REPLACES the dots.' },
  { name: 'flow', desc: 'The dots AND the streamline arrows together in the one underlay canvas — particles drifting along the visible flow. No second blended surface, so it stays cheap.' },
  { name: 'knockout', desc: 'Figure-ground inversion — the field paints a solid accent wash and matter is punched out as negative space (a print knockout). Clip the canvas to real type with a CSS mask for the field-inside-letters treatment; matter never assembles into letterforms.' },
  { name: 'redshift', desc: 'Dots tinted by spectral shift instead of the heat ramp — Doppler from each particle\'s radial velocity (receding reds, approaching blues) plus a gravitational red near body wells. The relativistic accretion-disk look.' },
  { name: 'blackbody', desc: 'Dots tinted by energy on a thermal ramp — near-black ember → deep red → orange → warm white → blue-white — with brightness rising with temperature. Physically-warm color, not radiometry.' },
  { name: 'depth', desc: 'The z lane made visible (2.5D) — far-to-near painter\'s sorting so near matter occludes far, perspective parallax toward the viewport centre, and defocus with distance. Pairs with a depth > 0 field; identical geometry to dots when flat.' },
];

/** Field Surfaces — the overlay READINGS (`field.setOverlay`). Line/text diagnostics drawn in front of
 *  content; additive — pass one, or a stack (array / space-separated attribute) and they compose. */
export const OVERLAY_MODES: { name: string; desc: string }[] = [
  { name: 'streamlines', desc: 'Arrows along the net push a still probe would feel — vector flow, felt.' },
  { name: 'force-vectors', desc: 'The same arrows scaled by raw magnitude — strong forces read strong, weak stay faint.' },
  { name: 'field-lines', desc: 'Arrows along the structure-only field (dipoles / monopoles) — the geometry, not the felt push.' },
  { name: 'grid', desc: 'A reference lattice displaced by the local field — space itself made visible, bending where the field is strong.' },
  { name: 'temperature', desc: 'Iso-contour rings of accumulated particle heat — the thermal field, drawn as lines so it never paints over content.' },
  { name: 'energy', desc: 'Iso-contour rings of kinetic energy (½m·|v|²) — where the motion is.' },
  { name: 'path', desc: 'Streamline curves traced from seeded probes — where the field would carry a particle over distance.' },
  { name: 'data', desc: 'A numeric density readout beside each measuring body — the --d measurement made legible.' },
];

/** Observed HTML attributes on `<field-root>` — the HTML face of the createField options.
 *  These are the attrs you set in markup / Astro / JSX; each mirrors a createField option (camelCase).
 *  The matching createField option entry in OPTIONS[] has the full description. */
export const FIELD_ROOT_ATTRS: { name: string; option: string; desc: string }[] = [
  { name: 'accent', option: 'accent', desc: 'Travelling accent color hex. Mirrors the accent createField option.' },
  { name: 'density', option: 'density', desc: 'Particle-count multiplier. Mirrors the density createField option.' },
  { name: 'waves', option: 'waves', desc: 'Draw background Currents. Mirrors the waves option (opt-in boolean attribute, #979 — presence = on, absence = off).' },
  { name: 'depth', option: 'depth', desc: 'Optional z volume for a shallow 3D effect. Mirrors the depth createField option.' },
  { name: 'integrator', option: 'integrator', desc: "Integration scheme: 'fixed' opts into the partially frame-rate-corrected integrator (dt-scales the decays, not force impulses — doc-04 §Step 3), 'velocity-verlet' into the second-order Verlet scheme (#659); default 'legacy'. Mirrors the integrator createField option. Experimental." },
  { name: 'render', option: 'render', desc: 'Underlay render mode (none / dots / trails / links / metaballs / voronoi / streamlines / flow / knockout / redshift / blackbody / depth). Mirrors the render createField option.' },
  { name: 'overlay', option: 'overlay', desc: 'Overlay reading(s) drawn in front of content — one or space-separated stack. Mirrors the overlay createField option.' },
  { name: 'palette', option: 'palette', desc: 'Accent color template (built-in name or hex stops, space-separated). Mirrors the palette option.' },
  { name: 'mass', option: 'mass', desc: 'First-class mass (boolean). Mirrors the mass createField option.' },
  { name: 'attention', option: 'attention', desc: 'Conserved attention (boolean). Mirrors the attention createField option.' },
  { name: 'causality', option: 'causality', desc: 'Cross-boundary causality (boolean). Mirrors the causality createField option.' },
  { name: 'heatmap', option: 'heatmap', desc: 'Density heatmap (boolean). Mirrors the heatmap createField option.' },
  { name: 'dpr-cap', option: 'dprCap', desc: 'Backing-store DPR ceiling (number). Mirrors the dprCap createField option.' },
  { name: 'grid-warp', option: 'gridWarp', desc: 'Grid overlay distortion multiplier. Mirrors the gridWarp createField option.' },
  { name: 'grid-intensity', option: 'gridIntensity', desc: 'Grid overlay stroke intensity. Mirrors the gridIntensity createField option.' },
  { name: 'theme', option: 'theme', desc: 'Ambient theme preset (warm / cool / mono). Mirrors the theme createField option.' },
  { name: 'gradient-cool', option: 'gradientCool', desc: 'Cool-end hex for the particle heat ramp. Mirrors the gradientCool createField option.' },
  { name: 'gradient-warm', option: 'gradientWarm', desc: 'Warm-end hex for the particle heat ramp. Mirrors the gradientWarm createField option.' },
  { name: 'wave-baseline', option: 'waveBaseline', desc: 'Hex stops for the background-wave baseline (space-separated). Mirrors the waveBaseline createField option.' },
  { name: 'wave-style', option: 'waveStyle', desc: "Wave current pattern (linear / circular). Mirrors the waveStyle createField option." },
  { name: 'wave-center', option: 'waveCenter', desc: 'Center coordinate for circular waves (space-separated x y). Mirrors the waveCenter createField option.' },
  { name: 'separation', option: 'separation', desc: 'Short-range particle separation strength. Mirrors the separation createField option.' },
  { name: 'ambient-orbit', option: 'ambientOrbit', desc: 'DECLARED resting-formation swirl on attract (#978); 0 for a purely radial attract. Mirrors the ambientOrbit createField option.' },
  { name: 'ambient-wander', option: 'ambientWander', desc: 'DECLARED resting-formation drift (#978); lower for a calmer rest, 0 to still it. Mirrors the ambientWander createField option.' },
  { name: 'background', option: 'background', desc: "Substrate background (opaque / transparent). Mirrors the background createField option." },
  { name: 'formation', option: 'formation', desc: 'Global formation preset name. Mirrors the formation createField option (setFormation).' },
];
