/**
 * The frozen public API surface for field-ui `0.x` — the single data source shared by the lock
 * (`scripts/check-api-surface.mjs`) and the docs page (`/docs/api/stability`). The prose contract is
 * `docs/canonical/field-ui-api-stability.md`; the hard type/value gate is `scripts/api-surface.ts`.
 *
 * Editing this list changes the public contract. Per the compatibility rules below, removing,
 * renaming, or changing the kind/shape of any frozen entry is a BREAKING change (a 0.MINOR bump in
 * the 0.x line) and needs a CHANGELOG migration note. Additions are fine in a PATCH.
 *
 * Package npm names: core = `field-ui`, others = `@field-ui/{platform,elements,react,vanilla}`.
 */

/** Frozen value exports — functions/consts that must remain importable, with their owning package. */
export const FROZEN_VALUES = [
  { pkg: '@field-ui/core', name: 'createField', note: 'host-required primitive — throws without opts.host (the renderer-agnostic door).' },
  { pkg: '@field-ui/core', name: 'compileRecipe', note: 'pure FieldRecipe → compiled plan (no DOM).' },
  { pkg: '@field-ui/platform', name: 'browserHost', note: 'the canonical DOM FieldHost for core.createField.' },
  { pkg: '@field-ui/platform', name: 'createFieldPlatform', note: 'wires the six native-first registries on a root.' },
  { pkg: '@field-ui/platform', name: 'applyRecipe', note: 'applies a recipe to a live platform (compileRecipe lives in core).' },
  { pkg: '@field-ui/platform', name: 'bindData', note: 'binds records → bodies; data drives the field.' },
  { pkg: '@field-ui/vanilla', name: 'createField', note: 'host-bundled convenience = createBrowserField (auto-supplies browserHost).' },
  { pkg: '@field-ui/vanilla', name: 'browserHost', note: 're-export of the platform host for the no-framework path.' },
];

/** Frozen type exports — interfaces that must remain exported, with their owning package. */
export const FROZEN_TYPES = [
  { pkg: '@field-ui/core', name: 'FieldRecipe', note: 'the recipe schema (recipes/schema.ts).' },
  { pkg: '@field-ui/core', name: 'FieldHost', note: 'the renderer-agnostic host contract createField requires; browserHost implements it.' },
  { pkg: '@field-ui/platform', name: 'FieldPlatform', note: 'the surface createFieldPlatform returns.' },
];

/** Frozen custom-element tag names, owned by @field-ui/elements (field-* names; forces-* are deprecated aliases). */
export const FROZEN_ELEMENTS = [
  { pkg: '@field-ui/elements', tag: 'field-root', note: 'one background field per page; scans the document for [data-body]. Alias of deprecated <forces-field>.' },
  { pkg: '@field-ui/elements', tag: 'field-cell', note: 'a scoped local field region. Alias of deprecated <forces-cell>.' },
];

/**
 * The body contract is an ATTRIBUTE, not an element. "Every element is a body" via `data-body` on
 * ordinary elements (core BODY_SELECTOR). There is NO <field-body> tag and one must not be introduced
 * as the body mechanism.
 */
export const FROZEN_BODY_ATTR = 'data-body';

/** Experimental surface — explicitly NOT frozen; may change shape or be removed in any release. */
export const EXPERIMENTAL = [
  { item: 'FieldHandle — full shape', status: 'partial', note: 'The entry points that return FieldHandle are frozen; the handle shape itself is not. New methods may be added in any patch.' },
  { item: 'FieldHandle.particleCount() / .energy()', status: 'partial', note: 'Shipped in @field-ui/core and proxied on <field-root>. Safe to use; signatures may refine before 1.0 as FieldPerf is designed.' },
  { item: 'FieldHandle.readParticles(out)', status: 'partial', note: 'Shipped in @field-ui/core. Copies live particle state into a caller-owned Float32Array (stride 4: x, y, heat, size, in CSS-pixel field coords) and returns the count written = min(particleCount(), floor(out.length/4)). Zero-alloc, read-only; the render-agnostic swarm read-out @field-ui/three\'s particle bridge consumes. Additive to the (unfrozen) handle shape; stride may widen via overload before 1.0.' },
  { item: 'FieldHandle.scrollV()', status: 'partial', note: 'Shipped in @field-ui/core; returns the engine\'s EMA scroll velocity in px/frame (refresh-rate dependent — reads roughly half on a 120 Hz display). Mirrored as --field-scroll-v on :root by the platform runtime. Signature stable; semantics (the unit may normalize to px/ms, EMA factor) may refine before 1.0.' },
  { item: "render mode 'none' (signals-only engine)", status: 'partial', note: 'Shipped in @field-ui/core (#297): createField({ render: \'none\' }) runs the full simulation + feedback pipeline but never acquires a canvas context, never sizes the backing store (it stays 0×0), and never draws — the field exists purely as signals (--d, --load, --lit, capture events, scrollV). setRender FROM \'none\' acquires the context lazily; setRender TO \'none\' at runtime stops drawing but keeps an already-acquired context. Accepted by <field-root render="none">. Shipped-but-unfrozen; may refine before being added to the frozen list.' },
  { item: 'QualityGovernor / field:quality-tier', status: 'partial', note: 'Tier detection (0-3) ships in @field-ui/platform; the <field-root> runtime throttles its own tick cadence at tiers 2-3 and emits field:quality-tier. Engine-side degradation (render simplification, particle caps) is the embedder\'s to wire; unfrozen.' },
  { item: 'performance budget (inspectBudget / DEFAULT_BUDGET / createFieldPerf)', status: 'partial', note: 'inspectBudget(), withinBudget(), BudgetFinding, and DEFAULT_BUDGET ship in @field-ui/core. QualityGovernor covers adaptive tier detection. The FieldPerf frame-duration split now ships in @field-ui/platform as createFieldPerf() — pure timing math lifted from the site DataConsole prototype (rolling delta window of 180, nearest-rank-floor percentiles, budget = median of the first 30 clean deltas, dropped = delta > budget×1.5, gaps > 500 ms skipped as discontinuities; callers feed rAF timestamps — no rAF of its own). The LoAF / long-task split stays page-side (no PerformanceObserver in this slice). Unfrozen — option/snapshot shapes may refine before 1.0.' },
  { item: 'advanced diagnostics', status: 'partial', note: 'DIAGNOSTICS / DIAGNOSTIC_LENS / draw* primitives ship today but are shipped-but-unfrozen until added here.' },
  { item: 'visual recipe editor', status: 'absent', note: 'no editor UI; the authoring toolkit (compileRecipe/recipeAuthoring/validateRecipe) is the substrate to build one on.' },
  { item: 'GPU / WebGPU backend', status: 'planned', note: 'a named direction (VisualBindingRegistry mentions WebGL); the six shipped drawing render modes are CPU/canvas (the seventh, \'none\', draws nothing).' },
  { item: 'multi-root bridge', status: 'absent', note: 'no API for coordinating multiple <field-root> instances yet.' },
  { item: 'AI evidence fields', status: 'partial', note: 'EVIDENCE_FIELD + the agent API ship as a substrate, but no packaged feature; unfrozen.' },
  { item: 'custom render backends', status: 'partial', note: 'a custom backend is possible via opts.host, but there is no stable backend-registration API.' },
  { item: 'withFlip()', status: 'partial', note: 'Shipped in @field-ui/platform; a pure DOM FLIP reflow helper (measure → mutate → invert → release) extracted from the invisible-fields example runtimes (#295). No registry dependencies; honors prefers-reduced-motion (the mutation still runs). Unfrozen — the options shape may refine before 1.0.' },
  { item: 'allocateAttention()', status: 'partial', note: 'Shipped in @field-ui/core; a pure conserved-attention allocator (water-filling: Σw pinned to one finite budget, per-item cap defaulting to 1, capped excess re-flows, pinned items take exactly cap off the top) extracted from the Inbox example runtime (#296). Pure and deterministic — no DOM. Unfrozen — the item/options shapes may refine before 1.0.' },
  { item: 'textBodies()', status: 'partial', note: 'Shipped in @field-ui/platform — the Range-geometry slice of #257: samples a text element\'s rendered line/word boxes (document.createRange + getClientRects) into aria-hidden wall/shear boundary spans bound back to the source via data-field-visual-for (role representation), so the field flows around/along the words. Box geometry, not glyph contours — glyph-outline sampling is the planned next slice; callers re-annotate on resize. Unfrozen — the options/handle shapes may refine before 1.0.' },
  { item: 'threadOverlay()', status: 'partial', note: 'Shipped in @field-ui/platform; the hover-thread SVG overlay extracted from three hand-rolled copies in the example family (Evidence wireThreads/centerIn, Backlog, Dependencies). Geometry + classes only — one absolutely-positioned aria-hidden pointer-events:none SVG prepended into a host (viewBox from the host rect), one host-relative center-to-center cubic bezier per target (midpoint-y shape), --thread set from draw()\'s color, .lit/.cited marks on the endpoints. NO event wiring (pages own hover semantics) and no layout observation (callers re-draw on layout changes). Unfrozen — shapes may refine before 1.0.' },
  { item: 'applyRecipe renderless / extraMetrics options', status: 'partial', note: 'Shipped in @field-ui/platform; the scoped invisible-field idiom the twelve example runtimes hand-spread (render: [] + metrics dedupe-append) lifted into ApplyRecipeOptions. Both derive an EFFECTIVE recipe copy inside applyRecipe — the caller\'s (possibly shared catalog) recipe object is never mutated; the returned handle\'s recipe/compiled reflect the effective one. Additive — existing call shapes unchanged. Unfrozen — option names may refine before 1.0.' },
  { item: 'bindFieldNav() + classifyMetric() / lintInertFeedback', status: 'partial', note: 'Shipped in @field-ui/platform; the navigation-chrome idiom the site hand-spread across ~12 surfaces (top nav, chapter rail, docs sidebar/outline/search, breadcrumbs, pagers, footer, filter rosters) lifted into bindFieldNav(root, recipe, { pin, visited, extraMetrics, reducedMotion }): runs a recipe signals-only (render: []) over the <a href> links, pins the current as the well (data-field-attention=1), marks caller-flagged visited links (data-field-memory=1 + a nav-visited class), and returns a teardown; reduced-motion → null (plain links). Paired guard: classifyMetric(name) splits a lane into computed / supplied-only / designed (COMPUTED_METRICS + SUPPLIED_ONLY_METRICS partition METRIC_KINDS), and the new lintInertFeedback rule (in lintPlatform) flags a feedback binding to a DESIGNED --field-<m> lane the host never supplies — declared but never written, the same silent-contract class as lintSinkFeedback. Unfrozen — option names + the designed/computed split may refine before 1.0.' },
  { item: '`screen` modifier (quiet zones)', status: 'partial', note: 'Shipped in @field-ui/core (physics workover v0.3): a body with `screen` in data-body damps OTHER bodies\' forces on matter inside its data-range — clamp(1 − S·(1 − d/r)², data-screen-min, 1), applied in the integrator force pass (smooth edge, no NaN at zero range, never global). Passported (truth mode: designed, class modifier) with a conformance scenario. The data-body attribute contract itself is frozen; this TOKEN and its data-screen-* attrs are unfrozen — data-screen-mode (inside/outside/behind) is planned and the attenuation curve may refine before 1.0.' },
  { item: 'measured thermodynamics (--entropy / --coherence / --temperature)', status: 'partial', note: 'Shipped in @field-ui/core (physics workover v0.3): per-body LOCAL measurements on data-feedback bodies — entropy = (1 − R)·min(1, s̄/1.5) with R = |Σv|/Σ|v| (velocity alignment), coherence = 1 − entropy, temperature = ½·meanHeat + ½·min(1, s̄²/9) — accumulated in the existing density pass (core/thermo.ts is the pure math), eased like --d, and written through both feedback sinks as the bare names --entropy/--coherence/--temperature. Distinct from the platform\'s inferred --field-entropy/--field-coherence lanes and from the --coherence palette COLOR cssTokens() sets on :root. Unfrozen — the formulas\' reference constants and the FeedbackChannels fields may refine before 1.0.' },
  { item: 'source budget (data-life / data-cap + the unbudgeted-source guard)', status: 'partial', note: 'Shipped in @field-ui/core (physics workover v0.3): a class-[S] source body (spawn) must declare one of data-life / data-cap / data-budget / data-sink; otherwise the scanner warns in dev (naming the element) and applies the safe defaults data-life="300" / data-cap="120". data-life sets each emission\'s mortal age; data-cap clamps the emission rate to cap/life so the body\'s live population is bounded at ~cap. Conformance pins the bound. Unfrozen — data-budget/data-sink carry presence-only semantics today and may gain richer ones.' },
  { item: 'weight primitives (logNormalize/weightToStrength)', status: 'partial', note: 'Shipped in @field-ui/core (core/weights.ts): the page-weight → body-strength contract extracted from ~38 hand-rolled call sites in the example family. logNormalize(value, max) is the family\'s log "consensus" shape — ln(value+1)/ln(max+1), clamped 0..1; heavy tails compress, zero stays zero, value === max reads exactly 1 (bit-for-bit the pages\' Math.log(x+1)/Math.log(max+1) for max > 0). logNormalizeAll(values) runs the set in one pass and returns the max for live re-normalization. weightToStrength(w) maps the 0..1 weight onto the attract-body data-strength range: 0.4 + w·1.6 → 0.4..2.0, with WEIGHT_STRENGTH_BASE/WEIGHT_STRENGTH_SPAN exported so the magic numbers have ONE definition (returns the number; callers .toFixed(2) at the attribute write). Pure and deterministic — no DOM, NaN-safe on degenerate inputs. Unfrozen — names and shapes may refine before 1.0.' },
  { item: 'temporal kernels (imminence/freshness/retention/phase) + data-field-at', status: 'partial', note: 'Shipped in @field-ui/core (core/temporal.ts): the world-time clock — pure, deterministic kernels extracted from the example family. imminence(at, now, horizon) log-ramps to 1 at T−0 (the calendar page); freshness(at, now, halfLife) is exponential newness, exactly 0.5 one half-life out (staleness = 1 − freshness; the backlog/inbox recency shape); retention(anchor, since, opts) is the Ebbinghaus curve with τ growing with anchor strength (the memory page); phase(now, period, offset) is cyclical 0..1 (consumer-less today, shipped for completeness). Riding on them in @field-ui/platform: a declared data-field-at (ISO 8601 or epoch ms; half-life via data-field-halflife, default 7 days) GROUNDS the metric pipeline\'s recency lane in world time — without it, recency stays interaction-inferred. World time is the third clock, alongside simulation time (env.t/dt) and experiential time (the metric pipeline); see docs/canonical/field-ui-time.md. Unfrozen — names, option shapes, and the attribute contract may refine before 1.0.' },
];

/** Compatibility rules for the 0.x line. */
export const COMPAT_RULES = [
  'Pre-1.0 semver: in 0.x the MINOR is the breaking position. A breaking change to any frozen symbol bumps 0.MINOR (e.g. 0.2 → 0.3); additive and fix-only changes bump PATCH. Consumers should pin to ~0.MINOR.',
  'The stable surface is additive-only within a 0.MINOR line: new exports, new optional fields, and new recipes/modes may land in a PATCH; renaming, removing, or changing the signature/shape of a frozen symbol requires a MINOR bump and a migration note.',
  'createField is frozen in BOTH field-ui (host-required primitive; throws without opts.host) and @field-ui/vanilla (host-bundled convenience). Both contracts are preserved; the vanilla door must keep auto-supplying browserHost.',
  'Package ownership is part of the contract and must not drift within 0.x: compileRecipe / FieldRecipe / FieldHost are core (field-ui); createFieldPlatform / applyRecipe / bindData / FieldPlatform / browserHost are @field-ui/platform; field-root / field-cell are @field-ui/elements.',
  'Bodies are a stable ATTRIBUTE contract: [data-body] on ordinary elements is the frozen authoring surface. There is no <field-body> tag and none will be introduced as the body mechanism.',
  'forces-* → field-* alias window (deprecated, removal-gated): <forces-field>/<forces-cell>, ForcesField/ForcesCell/ForcesController, useForcesField, forces:* events, --forces-* vars, and the compat-* packages keep working behavior-identically through 0.x and emit @deprecated guidance, but are excluded from the additive-only guarantee and scheduled for removal on a MINOR bump with a CHANGELOG entry.',
  'The experimental surface carries no semver guarantee. Diagnostics/agent/render-mode exports that happen to ship today are shipped-but-unfrozen — treat them as experimental until explicitly added to the frozen list.',
];
