// The parity matrix is generated by reading port source and extracting parameter names. If that
// extraction invents a name, the invented name is published as a real cross-plane surface — and
// because it appears on one plane only, it reads as a GAP on the other two, which is the most
// misleading direction for it to fail (#1178). These pin the shapes that fooled it.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { paramNames, stripComments } from './gen-parity-matrix.mjs';

const names = (block) => [...paramNames(block)].sort();

test('a doc comment containing a colon is not read as a parameter', () => {
  // The exact shape that slipped through: prose is prose, and prose has colons.
  const block = '/** The tokens. note: this exists for the host. */\n  val tokens: List<String>,\n  val strength: Float = 1f,';
  assert.deepEqual(names(block), ['strength', 'tokens']);
});

test('a line comment containing a colon is not read as a parameter', () => {
  assert.deepEqual(names('val a: Int, // note: ignore me\n  val b: Int,'), ['a', 'b']);
});

test('a colon inside a string default is not read as a parameter', () => {
  // `https` is not a parameter. Stripping comments by regex would instead eat the `//` and
  // truncate the block, losing every parameter after it — hence a scanner.
  assert.deepEqual(names('val url: String = "https://example.com",\n  val depth: Int = 1,'), ['depth', 'url']);
});

test('an escaped quote inside a default does not run the scanner off the end', () => {
  assert.deepEqual(names('val q: String = "a\\"b: c", val z: Int'), ['q', 'z']);
});

test("a closure's own parameter label is still excluded", () => {
  // The behaviour the original function was written for; kept intact by the comment strip.
  assert.deepEqual(names('_ view: AnyObject, onChange: (x: Int) -> Void'), ['onChange', 'view']);
});

test('stripComments keeps the quotes so the block still reads as code', () => {
  assert.match(stripComments('val u: String = "x: y"'), /""/);
});
