// GeneratedForceCatalog.kt — AUTO-GENERATED by scripts/gen-force-catalog.mjs
// DO NOT EDIT. Run `node scripts/gen-force-catalog.mjs` (or `pnpm gen:force-catalog`) to regenerate.
// Source of truth: packages/core/src/contracts/passport.ts + packages/core/src/config/forces.config.ts
package com.fundamental.lab

/** A force's structural identity, generated from the JS passport. Blurbs live in Catalog.kt. */
class GeneratedForce(val token: String, val label: String, val group: String)

/** All 37 forces in the canonical catalog, single-sourced from the JS engine. */
val GENERATED_FORCES: List<GeneratedForce> = listOf(
    GeneratedForce("attract", "Attract", "Canonical"),
    GeneratedForce("repel", "Repel", "Canonical"),
    GeneratedForce("swirl", "Swirl", "Canonical"),
    GeneratedForce("stream", "Stream", "Canonical"),
    GeneratedForce("viscosity", "Viscosity", "Canonical"),
    GeneratedForce("jet", "Jet", "Canonical"),
    GeneratedForce("tether", "Tether", "Canonical"),
    GeneratedForce("wall", "Wall", "Canonical"),
    GeneratedForce("sink", "Sink", "Canonical"),
    GeneratedForce("gravity", "Gravity", "Natural"),
    GeneratedForce("charge", "Charge", "Natural"),
    GeneratedForce("magnetism", "Magnetism", "Natural"),
    GeneratedForce("thermal", "Thermal", "Natural"),
    GeneratedForce("collide", "Collide", "Natural"),
    GeneratedForce("diffuse", "Diffuse", "Natural"),
    GeneratedForce("propagate", "Propagate", "Natural"),
    GeneratedForce("memory", "Memory", "Natural"),
    GeneratedForce("fieldflow", "Fieldflow", "Extended"),
    GeneratedForce("lens", "Lens", "Extended"),
    GeneratedForce("gate", "Gate", "Extended"),
    GeneratedForce("buoyancy", "Buoyancy", "Extended"),
    GeneratedForce("shear", "Shear", "Extended"),
    GeneratedForce("crystallize", "Crystallize", "Extended"),
    GeneratedForce("align", "Align", "Extended"),
    GeneratedForce("wind", "Wind", "Extended"),
    GeneratedForce("cohesion", "Cohesion", "Extended"),
    GeneratedForce("pressure", "Pressure", "Extended"),
    GeneratedForce("hunt", "Hunt", "Extended"),
    GeneratedForce("spawn", "Spawn", "Extended"),
    GeneratedForce("link", "Link", "Extended"),
    GeneratedForce("morph", "Morph", "Extended"),
    GeneratedForce("resonate", "Resonate", "Extended"),
    GeneratedForce("spotlight", "Spotlight", "Extended"),
    GeneratedForce("screen", "Screen", "Extended"),
    GeneratedForce("pigment", "Pigment", "Extended"),
    GeneratedForce("relief", "Relief", "Extended"),
    GeneratedForce("warp", "Warp", "Extended")
)
