import org.jetbrains.kotlin.gradle.dsl.JvmTarget

// @fundamental-engine/core, in Kotlin. Pure JVM — no Android imports — so it runs on the cheap CI
// runner and the conformance test exercises exactly the portable engine (mirror of FundamentalCore).
plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
}

dependencies {
    // type-safe decode of the cross-plane golden vectors (test-only)
    testImplementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    testImplementation(kotlin("test-junit5"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Bytecode target is pinned to 17 regardless of the JDK running Gradle, so local (JDK 23) and CI
// (Temurin 17) produce identical output. Java + Kotlin targets must agree (Gradle validates this).
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

tasks.test {
    useJUnitPlatform()
}

// ── Cross-plane conformance golden — single source of truth ──────────────────────────────────────
// The golden JSON is owned by the Swift test bundle and regenerated by `pnpm gen:golden`. We sync
// (never copy-commit) it onto the Kotlin test classpath so JS, Swift, and Android can never silently
// disagree on the force math. Path is repo-relative: this module sits at android/fundamental-core.
val goldenSource = rootProject.file("../swift/Tests/FundamentalCoreTests/Fixtures/conformance-golden.json")

val syncGolden by tasks.registering(Copy::class) {
    description = "Sync the canonical cross-plane conformance golden into test resources."
    from(goldenSource)
    into(layout.buildDirectory.dir("golden-resources/fixtures"))
}

sourceSets.test {
    resources.srcDir(layout.buildDirectory.dir("golden-resources"))
}

tasks.named<ProcessResources>("processTestResources") {
    dependsOn(syncGolden)
}
