import org.jetbrains.kotlin.gradle.dsl.JvmTarget

// @fundamental-engine/core, in Kotlin. Pure JVM — no Android imports — so it runs on the cheap CI
// runner and the conformance test exercises exactly the portable engine (mirror of FundamentalCore).
plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
}

dependencies {
    // decode the embedded 64-recipe canon at runtime + the cross-plane golden in tests.
    // kotlinx-serialization is pure Kotlin (no Android), so the core stays platform-free.
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    testImplementation(kotlin("test-junit5"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Bytecode target is pinned to 17 regardless of the JDK running Gradle, so local (JDK 23) and CI
// (Temurin 17) produce identical output. Java + Kotlin targets must agree (Gradle validates this).
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

tasks.test {
    useJUnitPlatform()
}

// ── Cross-plane conformance golden — single source of truth ──────────────────────────────────────
// The golden JSON is owned by the Swift test bundle and regenerated by `pnpm gen:golden`. We sync
// (never copy-commit) it onto the Kotlin test classpath so JS, Swift, and Android can never silently
// disagree on the force math. Path is repo-relative: this module sits at android/fundamental-core.
val goldenSource = rootProject.file("../swift/Tests/FundamentalCoreTests/Fixtures/conformance-golden.json")

val syncGolden by tasks.registering(Copy::class) {
    description = "Sync the canonical cross-plane conformance golden into test resources."
    from(goldenSource)
    into(layout.buildDirectory.dir("golden-resources/fixtures"))
}

// ── FIELD_VERSION lockstep — canonical version source ────────────────────────────────────────────
// The canonical engine version is the JS core's package version (`packages/core/package.json` — the
// same file `version.test.ts` locks the JS FIELD_VERSION to). Synced onto the test classpath, same
// mechanism as the golden, so `VersionLockstepTests` fails the build if a release bump leaves the
// Kotlin FIELD_VERSION stale (#923).
val coreVersionSource = rootProject.file("../packages/core/package.json")

val syncCoreVersion by tasks.registering(Copy::class) {
    description = "Sync the canonical core package.json (the version source) into test resources."
    from(coreVersionSource)
    into(layout.buildDirectory.dir("version-resources/version"))
}

sourceSets.test {
    resources.srcDir(layout.buildDirectory.dir("golden-resources"))
    resources.srcDir(layout.buildDirectory.dir("version-resources"))
}

tasks.named<ProcessResources>("processTestResources") {
    dependsOn(syncGolden)
    dependsOn(syncCoreVersion)
}

// ── The locked 64-recipe canon — single source of truth ──────────────────────────────────────────
// `data/recipes.json` is the shared canon (same file the JS catalog and Swift bundle use). We sync it
// onto the main classpath so `FieldRecipes` decodes the identical 64 recipes — never hand-retyped.
val recipesSource = rootProject.file("../data/recipes.json")

val syncRecipes by tasks.registering(Copy::class) {
    description = "Sync the locked 64-recipe canon into main resources."
    from(recipesSource)
    into(layout.buildDirectory.dir("recipe-resources"))
}

sourceSets.main {
    resources.srcDir(layout.buildDirectory.dir("recipe-resources"))
}

tasks.named<ProcessResources>("processResources") {
    dependsOn(syncRecipes)
}
